coverage:
  ignore:
  - Pods/.*
  - Applications/Xcode.app/.*
  - ci/.*
  - Carthage/.*
  - build/.*
  - Tests/.*
  - .*Tests.m
  status:
    patch:
      default:
        target: '80'
    project:
      default:
        target: auto
